// Implementation file for parser generated by fsyacc
module Parser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open Microsoft.FSharp.Text.Lexing
open Microsoft.FSharp.Text.Parsing.ParseHelpers
# 1 "Parser.fsy"

#indent "off"

open Generators
open System.Diagnostics

# 13 "Parser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | EOF
  | ZERO_OR_ONE
  | ZERO_OR_MORE
  | ONE_OR_MORE
  | ESCAPE of (string)
  | RANGE of (char*char)
  | LITERAL of (string)
  | OPEN_SET
  | CLOSE_SET
  | OPEN_PARENTHESIS
  | CLOSE_PARENTHESIS
  | ANY_CHAR
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_EOF
    | TOKEN_ZERO_OR_ONE
    | TOKEN_ZERO_OR_MORE
    | TOKEN_ONE_OR_MORE
    | TOKEN_ESCAPE
    | TOKEN_RANGE
    | TOKEN_LITERAL
    | TOKEN_OPEN_SET
    | TOKEN_CLOSE_SET
    | TOKEN_OPEN_PARENTHESIS
    | TOKEN_CLOSE_PARENTHESIS
    | TOKEN_ANY_CHAR
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstart
    | NONTERM_start
    | NONTERM_regEx
    | NONTERM_quantifier

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | EOF  -> 0 
  | ZERO_OR_ONE  -> 1 
  | ZERO_OR_MORE  -> 2 
  | ONE_OR_MORE  -> 3 
  | ESCAPE _ -> 4 
  | RANGE _ -> 5 
  | LITERAL _ -> 6 
  | OPEN_SET  -> 7 
  | CLOSE_SET  -> 8 
  | OPEN_PARENTHESIS  -> 9 
  | CLOSE_PARENTHESIS  -> 10 
  | ANY_CHAR  -> 11 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_EOF 
  | 1 -> TOKEN_ZERO_OR_ONE 
  | 2 -> TOKEN_ZERO_OR_MORE 
  | 3 -> TOKEN_ONE_OR_MORE 
  | 4 -> TOKEN_ESCAPE 
  | 5 -> TOKEN_RANGE 
  | 6 -> TOKEN_LITERAL 
  | 7 -> TOKEN_OPEN_SET 
  | 8 -> TOKEN_CLOSE_SET 
  | 9 -> TOKEN_OPEN_PARENTHESIS 
  | 10 -> TOKEN_CLOSE_PARENTHESIS 
  | 11 -> TOKEN_ANY_CHAR 
  | 14 -> TOKEN_end_of_input
  | 12 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstart 
    | 1 -> NONTERM_start 
    | 2 -> NONTERM_regEx 
    | 3 -> NONTERM_regEx 
    | 4 -> NONTERM_regEx 
    | 5 -> NONTERM_regEx 
    | 6 -> NONTERM_regEx 
    | 7 -> NONTERM_regEx 
    | 8 -> NONTERM_quantifier 
    | 9 -> NONTERM_quantifier 
    | 10 -> NONTERM_quantifier 
    | 11 -> NONTERM_quantifier 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 14 
let _fsyacc_tagOfErrorTerminal = 12

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | EOF  -> "EOF" 
  | ZERO_OR_ONE  -> "ZERO_OR_ONE" 
  | ZERO_OR_MORE  -> "ZERO_OR_MORE" 
  | ONE_OR_MORE  -> "ONE_OR_MORE" 
  | ESCAPE _ -> "ESCAPE" 
  | RANGE _ -> "RANGE" 
  | LITERAL _ -> "LITERAL" 
  | OPEN_SET  -> "OPEN_SET" 
  | CLOSE_SET  -> "CLOSE_SET" 
  | OPEN_PARENTHESIS  -> "OPEN_PARENTHESIS" 
  | CLOSE_PARENTHESIS  -> "CLOSE_PARENTHESIS" 
  | ANY_CHAR  -> "ANY_CHAR" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | EOF  -> (null : System.Object) 
  | ZERO_OR_ONE  -> (null : System.Object) 
  | ZERO_OR_MORE  -> (null : System.Object) 
  | ONE_OR_MORE  -> (null : System.Object) 
  | ESCAPE _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | RANGE _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | LITERAL _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | OPEN_SET  -> (null : System.Object) 
  | CLOSE_SET  -> (null : System.Object) 
  | OPEN_PARENTHESIS  -> (null : System.Object) 
  | CLOSE_PARENTHESIS  -> (null : System.Object) 
  | ANY_CHAR  -> (null : System.Object) 
let _fsyacc_gotos = [| 0us; 65535us; 1us; 65535us; 0us; 1us; 7us; 65535us; 0us; 2us; 4us; 5us; 7us; 8us; 10us; 11us; 13us; 14us; 16us; 17us; 21us; 22us; 5us; 65535us; 6us; 7us; 9us; 10us; 12us; 13us; 15us; 16us; 20us; 21us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 3us; 11us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 1us; 1us; 1us; 1us; 1us; 3us; 1us; 3us; 1us; 3us; 1us; 3us; 1us; 3us; 1us; 4us; 1us; 4us; 1us; 4us; 1us; 5us; 1us; 5us; 1us; 5us; 1us; 6us; 1us; 6us; 1us; 6us; 1us; 7us; 1us; 7us; 1us; 7us; 1us; 7us; 1us; 7us; 1us; 9us; 1us; 10us; 1us; 11us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 6us; 8us; 10us; 12us; 14us; 16us; 18us; 20us; 22us; 24us; 26us; 28us; 30us; 32us; 34us; 36us; 38us; 40us; 42us; 44us; 46us; 48us; 50us; |]
let _fsyacc_action_rows = 26
let _fsyacc_actionTableElements = [|5us; 16386us; 4us; 15us; 6us; 12us; 7us; 18us; 9us; 4us; 11us; 9us; 0us; 49152us; 1us; 32768us; 0us; 3us; 0us; 16385us; 5us; 16386us; 4us; 15us; 6us; 12us; 7us; 18us; 9us; 4us; 11us; 9us; 1us; 32768us; 10us; 6us; 3us; 16392us; 1us; 23us; 2us; 24us; 3us; 25us; 5us; 16386us; 4us; 15us; 6us; 12us; 7us; 18us; 9us; 4us; 11us; 9us; 0us; 16387us; 3us; 16392us; 1us; 23us; 2us; 24us; 3us; 25us; 5us; 16386us; 4us; 15us; 6us; 12us; 7us; 18us; 9us; 4us; 11us; 9us; 0us; 16388us; 3us; 16392us; 1us; 23us; 2us; 24us; 3us; 25us; 5us; 16386us; 4us; 15us; 6us; 12us; 7us; 18us; 9us; 4us; 11us; 9us; 0us; 16389us; 3us; 16392us; 1us; 23us; 2us; 24us; 3us; 25us; 5us; 16386us; 4us; 15us; 6us; 12us; 7us; 18us; 9us; 4us; 11us; 9us; 0us; 16390us; 1us; 32768us; 5us; 19us; 1us; 32768us; 8us; 20us; 3us; 16392us; 1us; 23us; 2us; 24us; 3us; 25us; 5us; 16386us; 4us; 15us; 6us; 12us; 7us; 18us; 9us; 4us; 11us; 9us; 0us; 16391us; 0us; 16393us; 0us; 16394us; 0us; 16395us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 6us; 7us; 9us; 10us; 16us; 18us; 22us; 28us; 29us; 33us; 39us; 40us; 44us; 50us; 51us; 55us; 61us; 62us; 64us; 66us; 70us; 76us; 77us; 78us; 79us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 2us; 0us; 5us; 3us; 3us; 3us; 5us; 0us; 1us; 1us; 1us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 2us; 2us; 2us; 2us; 2us; 2us; 3us; 3us; 3us; 3us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 65535us; 16385us; 65535us; 65535us; 65535us; 65535us; 16387us; 65535us; 65535us; 16388us; 65535us; 65535us; 16389us; 65535us; 65535us; 16390us; 65535us; 65535us; 65535us; 65535us; 16391us; 16393us; 16394us; 16395us; |]
let _fsyacc_reductions ()  =    [| 
# 148 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data :  regExGenerator )) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (Microsoft.FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startstart));
# 157 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'regEx)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 23 "Parser.fsy"
                                            fun () -> _1 ""  
                   )
# 23 "Parser.fsy"
                 :  regExGenerator ));
# 168 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 27 "Parser.fsy"
                         
                     			identityGen 
                     		
                   )
# 27 "Parser.fsy"
                 : 'regEx));
# 180 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'regEx)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : 'quantifier)) in
            let _5 = (let data = parseState.GetInput(5) in (Microsoft.FSharp.Core.Operators.unbox data : 'regEx)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 32 "Parser.fsy"
                        
                     			(_4 _2) >> _5
                     		
                   )
# 32 "Parser.fsy"
                 : 'regEx));
# 195 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'quantifier)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'regEx)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 37 "Parser.fsy"
                         
                     			(_2 charGen) >> _3
                     		
                   )
# 37 "Parser.fsy"
                 : 'regEx));
# 209 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'quantifier)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'regEx)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 42 "Parser.fsy"
                        
                     			_2(literalGen _1) >> _3
                     		
                   )
# 42 "Parser.fsy"
                 : 'regEx));
# 224 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'quantifier)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'regEx)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 47 "Parser.fsy"
                         
                     			_2(literalGen _1) >> _3
                     		
                   )
# 47 "Parser.fsy"
                 : 'regEx));
# 239 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : char*char)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : 'quantifier)) in
            let _5 = (let data = parseState.GetInput(5) in (Microsoft.FSharp.Core.Operators.unbox data : 'regEx)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 51 "Parser.fsy"
                        
                     			_4 ( rangeGen _2 ) >> _5
                     		
                   )
# 51 "Parser.fsy"
                 : 'regEx));
# 254 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 56 "Parser.fsy"
                               Quantifiers.one 
                   )
# 56 "Parser.fsy"
                 : 'quantifier));
# 264 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 57 "Parser.fsy"
                                        Quantifiers.zeroOrOne 
                   )
# 57 "Parser.fsy"
                 : 'quantifier));
# 274 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 58 "Parser.fsy"
                                         Quantifiers.zeroOrMore 
                   )
# 58 "Parser.fsy"
                 : 'quantifier));
# 284 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 59 "Parser.fsy"
                                        Quantifiers.oneOrMore 
                   )
# 59 "Parser.fsy"
                 : 'quantifier));
|]
# 295 "Parser.fs"
let tables () : Microsoft.FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:Microsoft.FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 15;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let start lexer lexbuf :  regExGenerator  =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
